import type { Metadata } from "next";
import "./globals.css";
import NavigationChecker from "./components/NavigationChecker/NavigationChecker";
import FooterChecker from "./components/NavigationChecker/FooterChecker";

export const metadata: Metadata = {
  title: "DMTas-development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavigationChecker />
        {children}
        <FooterChecker />
      </body>
    </html>
  );
}
